# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: Wiz Scanner Settings Updated
description: |-
  Detect when Wiz scanner settings are updated.
enabled: true
severity: Medium
query_text: |-
  @scnr.source_type:wiz
  action:UpdateScannerSettings
  status:SUCCESS
  | groupbycount(user.name)
  | where @q.count > 0
time_range_s: 300
run_frequency_s: 60
event_sink_keys:
- medium_severity_alerts
tags:
- tactics.ta0005.defense_evasion
- techniques.t1562.impair_defenses
- source.wiz
