# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: Wiz Login Settings Updated
description: |-
  Detect when Wiz login settings are updated. Unauthorized
  changes may impact authentication and access control.
enabled: true
severity: Medium
query_text: |-
  %ingest.source_type:"wiz:audit"
  action:UpdateLoginSettings
  status:SUCCESS
  | groupbycount(user.name)
  | where @q.count > 0
time_range_s: 300
run_frequency_s: 60
event_sink_keys:
- medium_severity_alerts
tags:
- tactics.ta0006.credential_access
- techniques.t1556.modify_authentication_process
- source.wiz
